=== AitorElorza/Sza/xml/erabiltzaileak.dtd
<!ELEMENT erabiltzaileak (erabiltzaile)*>

<!ELEMENT erabiltzaile (erabiltzailea,eposta,pasahitza)>
<!ELEMENT erabiltzailea (#PCDATA)>
<!ELEMENT eposta (#PCDATA)>
<!ELEMENT pasahitza (#PCDATA)>

=== AitorElorza/Sza/xml/erabiltzaileak.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE erabiltzaileak SYSTEM "erabiltzaileak.dtd">
<erabiltzaileak>
<erabiltzaile><erabiltzailea>a</erabiltzailea><eposta>aelorza@ikasle.es</eposta><pasahitza>a</pasahitza></erabiltzaile><erabiltzaile><erabiltzailea>kljj</erabiltzailea><eposta>aelorza003@ikasle.es</eposta><pasahitza>a</pasahitza></erabiltzaile></erabiltzaileak>
